language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-siegmeyer2' ]; then cd .. && eval "mv $currentfolder generator-siegmeyer2" && cd generator-siegmeyer2; fi

